spring:
  application:
    name: spring-cloud-eureka-consumer

server:
  port: 8200

#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false

feign:
  hystrix:
    enabled: true

eureka:
  client:
    service-url: {"defaultZone": "http://localhost:8000/eureka/"}
