server:
  port: 10000

zuul:
  routes:
    provider-api:
      path: /provider/**
      serviceId: spring-cloud-eureka-provider
    user-api:
      path: /user/**
      serviceId: spring-cloud-userprovider
    order-api:
      path: /order/**
      serviceId: spring-cloud-orderprovider

spring:
  application:
    name: spring-cloud-zuul
  zipkin:
    base-url: http://localhost:11000

eureka:
  client:
    service-url: {"defaultZone": "http://localhost:8000/eureka/"}
