spring:
  application:
    name: spring-cloud-orderprovider
  zipkin:
    base-url: http://localhost:11000
  sleuth:
    sampler:
      percentage: 1.0

server:
  port: 8101
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false

eureka:
  client:
    service-url: {"defaultZone": "http://localhost:8000/eureka/"}
